create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create or replace function public.is_registry_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.admin_users where user_id = (select auth.uid())
  );
$$;

create table if not exists public.gifts (
  id uuid primary key default gen_random_uuid(),
  title text not null check (char_length(title) between 2 and 120),
  description text not null default '' check (char_length(description) <= 2000),
  category text not null default 'Outros' check (char_length(category) between 2 and 60),
  gift_mode text not null default 'unit' check (gift_mode in ('unit', 'quota')),
  price_cents integer not null check (price_cents between 500 and 100000000),
  minimum_contribution_cents integer,
  quantity_total integer not null default 1 check (quantity_total between 1 and 100),
  image_path text,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint quota_minimum_is_valid check (
    (gift_mode = 'unit' and minimum_contribution_cents is null)
    or
    (gift_mode = 'quota' and minimum_contribution_cents between 500 and price_cents)
  )
);

create table if not exists public.gift_orders (
  id uuid primary key default gen_random_uuid(),
  gift_id uuid not null references public.gifts(id) on delete restrict,
  guest_name text not null check (char_length(guest_name) between 2 and 120),
  guest_email text not null check (char_length(guest_email) between 5 and 254),
  guest_message text not null default '' check (char_length(guest_message) <= 1000),
  public_name boolean not null default false,
  amount_cents integer not null check (amount_cents between 500 and 100000000),
  quantity integer not null default 1 check (quantity between 1 and 100),
  status text not null default 'created' check (
    status in ('created', 'pending', 'approved', 'rejected', 'cancelled', 'refunded', 'expired', 'review')
  ),
  mercado_pago_preference_id text unique,
  mercado_pago_payment_id text unique,
  payment_method text,
  external_reference text not null unique,
  expires_at timestamptz not null default (now() + interval '30 minutes'),
  paid_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.payment_events (
  id bigint generated by default as identity primary key,
  provider_event_id text not null unique,
  resource_id text not null,
  action text,
  processed boolean not null default false,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.admin_audit_log (
  id bigint generated by default as identity primary key,
  admin_user_id uuid references auth.users(id) on delete set null,
  action text not null,
  entity_type text not null,
  entity_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists gift_orders_gift_status_idx
  on public.gift_orders(gift_id, status, expires_at);
create index if not exists gifts_active_sort_idx
  on public.gifts(is_active, sort_order, created_at);
create index if not exists gift_orders_created_idx
  on public.gift_orders(created_at desc);

drop trigger if exists gifts_set_updated_at on public.gifts;
create trigger gifts_set_updated_at
before update on public.gifts
for each row execute function public.set_updated_at();

drop trigger if exists gift_orders_set_updated_at on public.gift_orders;
create trigger gift_orders_set_updated_at
before update on public.gift_orders
for each row execute function public.set_updated_at();

alter table public.admin_users enable row level security;
alter table public.gifts enable row level security;
alter table public.gift_orders enable row level security;
alter table public.payment_events enable row level security;
alter table public.admin_audit_log enable row level security;

revoke all on public.admin_users, public.gifts, public.gift_orders,
  public.payment_events, public.admin_audit_log from anon, authenticated;
grant select on public.gifts to authenticated;
grant select, insert, update, delete on public.gifts to authenticated;
grant select on public.admin_users, public.gift_orders,
  public.payment_events, public.admin_audit_log to authenticated;

drop policy if exists "Admins can read own membership" on public.admin_users;
create policy "Admins can read own membership"
on public.admin_users for select to authenticated
using (user_id = (select auth.uid()));

drop policy if exists "Public can read active gifts" on public.gifts;
create policy "Public can read active gifts"
on public.gifts for select to anon, authenticated
using (is_active or public.is_registry_admin());

drop policy if exists "Admins can insert gifts" on public.gifts;
create policy "Admins can insert gifts"
on public.gifts for insert to authenticated
with check (public.is_registry_admin() and created_by = (select auth.uid()));

drop policy if exists "Admins can update gifts" on public.gifts;
create policy "Admins can update gifts"
on public.gifts for update to authenticated
using (public.is_registry_admin())
with check (public.is_registry_admin());

drop policy if exists "Admins can delete gifts" on public.gifts;
create policy "Admins can delete gifts"
on public.gifts for delete to authenticated
using (public.is_registry_admin());

drop policy if exists "Admins can read orders" on public.gift_orders;
create policy "Admins can read orders"
on public.gift_orders for select to authenticated
using (public.is_registry_admin());

drop policy if exists "Admins can read payment events" on public.payment_events;
create policy "Admins can read payment events"
on public.payment_events for select to authenticated
using (public.is_registry_admin());

drop policy if exists "Admins can read audit log" on public.admin_audit_log;
create policy "Admins can read audit log"
on public.admin_audit_log for select to authenticated
using (public.is_registry_admin());

create or replace function public.log_gift_admin_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  affected_id uuid;
begin
  affected_id := case when tg_op = 'DELETE' then old.id else new.id end;
  insert into public.admin_audit_log (admin_user_id, action, entity_type, entity_id)
  values ((select auth.uid()), lower(tg_op), 'gift', affected_id::text);
  return case when tg_op = 'DELETE' then old else new end;
end;
$$;

drop trigger if exists gifts_admin_audit on public.gifts;
create trigger gifts_admin_audit
after insert or update or delete on public.gifts
for each row execute function public.log_gift_admin_change();

revoke all on function public.log_gift_admin_change() from public, anon, authenticated;

create or replace function public.reserve_gift_order(
  p_gift_id uuid,
  p_guest_name text,
  p_guest_email text,
  p_guest_message text default '',
  p_public_name boolean default false,
  p_amount_cents integer default null,
  p_quantity integer default 1
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  selected_gift public.gifts%rowtype;
  committed_quantity integer;
  committed_amount bigint;
  final_amount integer;
  final_quantity integer;
  new_order_id uuid := gen_random_uuid();
begin
  if char_length(trim(p_guest_name)) not between 2 and 120 then
    raise exception 'invalid_guest_name';
  end if;
  if char_length(trim(p_guest_email)) not between 5 and 254 then
    raise exception 'invalid_guest_email';
  end if;
  if char_length(coalesce(p_guest_message, '')) > 1000 then
    raise exception 'invalid_guest_message';
  end if;

  select * into selected_gift
  from public.gifts
  where id = p_gift_id and is_active = true
  for update;

  if not found then
    raise exception 'gift_not_available';
  end if;

  if selected_gift.gift_mode = 'unit' then
    final_quantity := greatest(1, least(coalesce(p_quantity, 1), 100));
    select coalesce(sum(quantity), 0)::integer into committed_quantity
    from public.gift_orders
    where gift_id = selected_gift.id
      and (
        status = 'approved'
        or (status in ('created', 'pending') and expires_at > now())
      );

    if committed_quantity + final_quantity > selected_gift.quantity_total then
      raise exception 'gift_not_available';
    end if;
    if selected_gift.price_cents::bigint * final_quantity > 100000000 then
      raise exception 'invalid_order_amount';
    end if;
    final_amount := (selected_gift.price_cents::bigint * final_quantity)::integer;
  else
    final_quantity := 1;
    select coalesce(sum(amount_cents), 0)::bigint into committed_amount
    from public.gift_orders
    where gift_id = selected_gift.id
      and (
        status = 'approved'
        or (status in ('created', 'pending') and expires_at > now())
      );

    final_amount := coalesce(p_amount_cents, 0);
    if final_amount < selected_gift.minimum_contribution_cents
      or committed_amount + final_amount > selected_gift.price_cents then
      raise exception 'invalid_contribution_amount';
    end if;
  end if;

  insert into public.gift_orders (
    id, gift_id, guest_name, guest_email, guest_message, public_name,
    amount_cents, quantity, external_reference
  ) values (
    new_order_id, selected_gift.id, trim(p_guest_name), lower(trim(p_guest_email)),
    trim(coalesce(p_guest_message, '')), coalesce(p_public_name, false),
    final_amount, final_quantity, new_order_id::text
  );

  return new_order_id;
end;
$$;

revoke all on function public.reserve_gift_order(uuid, text, text, text, boolean, integer, integer) from public, anon, authenticated;
grant execute on function public.reserve_gift_order(uuid, text, text, text, boolean, integer, integer) to service_role;

create or replace view public.gift_catalog
with (security_barrier = true)
as
select
  g.id,
  g.title,
  g.description,
  g.category,
  g.gift_mode,
  g.price_cents,
  g.minimum_contribution_cents,
  g.quantity_total,
  g.image_path,
  g.sort_order,
  greatest(g.quantity_total - coalesce(s.committed_quantity, 0), 0) as available_quantity,
  greatest(g.price_cents - coalesce(s.committed_amount, 0), 0) as remaining_amount_cents
from public.gifts g
left join lateral (
  select
    coalesce(sum(o.quantity) filter (where g.gift_mode = 'unit'), 0)::integer as committed_quantity,
    coalesce(sum(o.amount_cents) filter (where g.gift_mode = 'quota'), 0)::bigint as committed_amount
  from public.gift_orders o
  where o.gift_id = g.id
    and (
      o.status = 'approved'
      or (o.status in ('created', 'pending') and o.expires_at > now())
    )
) s on true
where g.is_active = true;

revoke all on public.gift_catalog from public;
grant select on public.gift_catalog to anon, authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'gift-images', 'gift-images', true, 5242880,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Admins can upload gift images" on storage.objects;
create policy "Admins can upload gift images"
on storage.objects for insert to authenticated
with check (bucket_id = 'gift-images' and public.is_registry_admin());

drop policy if exists "Admins can update gift images" on storage.objects;
create policy "Admins can update gift images"
on storage.objects for update to authenticated
using (bucket_id = 'gift-images' and public.is_registry_admin())
with check (bucket_id = 'gift-images' and public.is_registry_admin());

drop policy if exists "Admins can delete gift images" on storage.objects;
create policy "Admins can delete gift images"
on storage.objects for delete to authenticated
using (bucket_id = 'gift-images' and public.is_registry_admin());
